# Generated by Django 4.2 on 2023-04-12 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='post_img')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imgCapa', models.ImageField(upload_to='post_img')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 4, 12, 17, 7, 57, 744235))),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.cidade')),
                ('fotos', models.ManyToManyField(blank=True, to='noticias.foto')),
            ],
        ),
    ]
