# Generated by Django 4.2 on 2023-04-12 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 17, 9, 25, 445026)),
        ),
    ]
