# Generated by Django 4.2 on 2023-04-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='data',
        ),
    ]
