# Generated by Django 4.2 on 2023-04-12 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_delete_author_noticia_date_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='post_img')),
            ],
        ),
        migrations.CreateModel(
            name='Jornal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('date_publicacao', models.DateField(default=datetime.datetime(2023, 4, 12, 19, 55, 58, 990768))),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 4, 12, 19, 55, 58, 989768)),
        ),
    ]
