# Generated by Django 4.2 on 2023-04-13 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_alter_foto_titulo_alter_noticia_date_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='fotos',
            field=models.ManyToManyField(related_name='noticias', to='noticias.foto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 10, 51, 56, 431821)),
        ),
    ]
