# Generated by Django 4.2 on 2023-04-13 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_remove_foto_noticia_noticia_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='date_publicacao',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 13, 6, 48, 775345)),
        ),
    ]
