# Generated by Django 4.2 on 2023-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropagandaLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='foto', max_length=100)),
                ('img', models.ImageField(upload_to='post_img')),
            ],
        ),
    ]
