# Generated by Django 4.2 on 2023-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propagandas', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='foto', max_length=100)),
                ('img', models.ImageField(upload_to='post_img')),
            ],
        ),
    ]
